# Generated by Django 4.2.1 on 2023-06-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_documentos',
                'ordering': ['nombre'],
            },
        ),
    ]
