# Generated by Django 4.2.1 on 2023-06-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_tipodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_seguros',
                'ordering': ['nombre'],
            },
        ),
    ]
