# Generated by Django 4.2.1 on 2023-06-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_tiposeguro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.tipodocumento')),
                ('tipo_seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.tiposeguro')),
            ],
            options={
                'db_table': 'pacientes',
                'ordering': ['nombre'],
            },
        ),
    ]
